name: Hello World With Input
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Your name'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Hello World
      run: echo "Hello, ${{ github.event.inputs.name }}!"
